---
- name: Create the /var/guacamole directory
  ansible.builtin.file:
    mode: u=rwx,g=rx,o=rx
    path: /var/guacamole
    state: directory

- name: Download and untar the guacamole-composition tarball
  ansible.builtin.unarchive:
    # Using a fixed creates: /var/guacamole/compose.yml here makes the
    # ansible.builtin.unarchive task skip on subsequent runs even if
    # guacamole_composition_version changes, in which case the role
    # wouldn't actually upgrade/downgrade the installed composition
    # when the desired version is updated.  Instead we key idempotence
    # to the version using a marker file whose file name includes the
    # value of guacamole_composition_version.
    #
    # See also the handler that this task calls.
    creates: >-
      /var/guacamole/.guacamole-composition-{{
      guacamole_composition_version }}.installed
    dest: /var/guacamole
    extra_opts:
      - --strip-components=1
    remote_src: true
    src: >
      https://api.github.com/repos/cisagov/guacamole-composition/tarball/v{{
      guacamole_composition_version }}
  notify: create installation marker

- name: Create the dbinit directory with the desired permissions
  ansible.builtin.file:
    mode: u=rwx,g=rwx,o=rwx
    path: /var/guacamole/dbinit
    state: directory

- name: Pull the Docker images used by the Guacamole Docker composition
  block:
    # Docker is only enabled in ansible-role-docker, but we need it to
    # actually be running in order to pull Docker images.
    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: >
        Pull Docker images used by the Guacamole Docker composition
      community.docker.docker_compose_v2_pull:
        project_src: /var/guacamole

- name: Update dummy username/password with real values
  ansible.builtin.copy:
    content: "{{ item.contents }}"
    dest: /var/guacamole/src/secrets/{{ item.filename }}
    mode: u=rw,g=rw,o=r
  loop:
    - filename: postgres-username
      contents: "{{ guacamole_postgres_username }}"
    - filename: postgres-password
      contents: "{{ guacamole_postgres_password }}"
    - filename: private-ssh-key
      contents: "{{ guacamole_private_ssh_key }}"
    - filename: rdp-username
      contents: "{{ guacamole_rdp_username }}"
    - filename: rdp-password
      contents: "{{ guacamole_rdp_password }}"
    - filename: vnc-username
      contents: "{{ guacamole_vnc_username }}"
    - filename: vnc-password
      contents: "{{ guacamole_vnc_password }}"
    - filename: windows-sftp-base
      contents: "{{ guacamole_windows_sftp_base }}"
  loop_control:
    label: "{{ item.filename }}"

- name: Configure guacamole service
  block:
    - name: Set up guacamole as a systemd service
      ansible.builtin.copy:
        dest: /lib/systemd/system/
        mode: u=rw,g=r,o=r
        src: guacamole-composition.service

    - name: Systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable guacamole systemd service
      ansible.builtin.systemd:
        enabled: true
        name: guacamole-composition.service

- name: Configure PAM for guacamole and guacamole-admin services
  ansible.builtin.copy:
    content: |
        auth    required   pam_sss.so
        account required   pam_sss.so
    dest: /etc/pam.d/{{ item }}
    mode: u=rw,g=r,o=r
  loop:
    - guacamole
    - guacamole-admin

# TODO - Fix below tasks for non-Debian hosts, so we can add support
# for them.
- name: Configure httpd for guacamole
  block:
    - name: Disable listening on port 80
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: Listen 80
        state: absent

    - name: Disable default httpd configuration
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    # This helps us with idempotence, since if we tell apache2ctl not
    # to check the config then it blindly tries to install all the
    # modules again when it installs cisagov/ansible-role-httpd a
    # second time and fails.
    - name: >-
        Create dummy non-empty SSL cert files so apache2ctl thinks the config
        is valid
      block:
        - name: Ensure cert directory exists
          ansible.builtin.file:
            mode: u=rwx,g=rx,o=rx
            path: /var/guacamole/httpd/ssl
            state: directory
        - name: Create dummy cert files
          ansible.builtin.copy:
            content: Hello
            dest: /var/guacamole/httpd/ssl/{{ item }}
            mode: u=rw,g=r,o=r
          loop:
            - self.cert
            - self-ssl.key

    - name: Copy guacamole httpd configuration
      ansible.builtin.copy:
        dest: /etc/apache2/sites-available/guacamole.conf
        mode: u=rw,g=r,o=r
        src: guacamole_httpd_config

    - name: Enable guacamole httpd configuration
      ansible.builtin.file:
        dest: /etc/apache2/sites-enabled/guacamole.conf
        src: /etc/apache2/sites-available/guacamole.conf
        state: link

- name: Copy setup script
  ansible.builtin.copy:
    dest: /usr/local/sbin
    mode: u=rx,g=,o=
    src: 02_setup_guacamole_services.sh
